title: whoami
author: whoami
email: whoamiapp2580@gmail.com
description: whoami is a service that aggregates your experience with your social media into one.
baseurl: "/"
url: "https://whoamiproject.github.io"

# Build settings
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default" # this ensures all content renders with layouts/default.html

plugins:
  - jekyll-feed
  - jekyll-menus

